// Package config — discovery.go implements walk-up discovery of a .hyoka
// project directory and path resolution that checks .hyoka/ subdirectories
// before falling back to repo-root paths.
package config

import (
	"log/slog"
	"os"
	"path/filepath"
)

// ProjectDirName is the sentinel directory name that marks a hyoka project.
const ProjectDirName = ".hyoka"

// ProjectSubdirs lists the subdirectories scaffolded inside .hyoka/.
var ProjectSubdirs = []string{
	"configs",
	"prompts",
	"criteria",
	"skills",
	"reports",
}

// ProjectDir holds the result of a .hyoka directory discovery.
type ProjectDir struct {
	// Root is the absolute path to the .hyoka directory (e.g. /repo/.hyoka).
	// Empty when no project directory was found.
	Root string
}

// Found reports whether a .hyoka directory was discovered.
func (p *ProjectDir) Found() bool { return p.Root != "" }

// SubDir returns the absolute path to a named subdirectory inside .hyoka
// (e.g. "configs" → /repo/.hyoka/configs). Returns "" if no project dir.
func (p *ProjectDir) SubDir(name string) string {
	if p.Root == "" {
		return ""
	}
	return filepath.Join(p.Root, name)
}

// DiscoverProjectDir walks up from startDir looking for a .hyoka directory.
// It stops at the Git repository root (a directory containing .git) or the
// filesystem root, whichever comes first.
func DiscoverProjectDir(startDir string) *ProjectDir {
	abs, err := filepath.Abs(startDir)
	if err != nil {
		slog.Debug("Failed to resolve absolute start dir for discovery", "dir", startDir, "error", err)
		return &ProjectDir{}
	}

	dir := abs
	for {
		candidate := filepath.Join(dir, ProjectDirName)
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			slog.Debug("Discovered .hyoka project directory", "path", candidate)
			return &ProjectDir{Root: candidate}
		}

		// Stop at git root — .hyoka must live within the repo.
		gitDir := filepath.Join(dir, ".git")
		if info, err := os.Stat(gitDir); err == nil && info.IsDir() {
			slog.Debug("Reached git root without finding .hyoka", "git_root", dir)
			return &ProjectDir{}
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Filesystem root reached.
			return &ProjectDir{}
		}
		dir = parent
	}
}

// DiscoverFromCWD is a convenience wrapper that starts discovery from the
// current working directory.
func DiscoverFromCWD() *ProjectDir {
	cwd, err := os.Getwd()
	if err != nil {
		slog.Debug("Failed to get CWD for project discovery", "error", err)
		return &ProjectDir{}
	}
	return DiscoverProjectDir(cwd)
}

// ResolveCandidates returns an ordered list of candidate paths for a given
// subdirectory name (e.g. "configs", "prompts"). The .hyoka/ path is checked
// first, followed by the legacy ./subdir and ../subdir fallbacks.
// Only paths that actually exist on disk are returned. Symlinks are resolved
// so that callers using filepath.Walk (which uses os.Lstat) see real directories.
func ResolveCandidates(proj *ProjectDir, subdir string, extraCandidates ...string) []string {
	var candidates []string

	// .hyoka/<subdir> takes priority
	if proj.Found() {
		hyokaPath := proj.SubDir(subdir)
		if resolved, ok := resolveIfDir(hyokaPath); ok {
			candidates = append(candidates, resolved)
		}
	}

	// Legacy fallback paths
	defaults := []string{"./" + subdir, "../" + subdir}
	defaults = append(defaults, extraCandidates...)
	for _, c := range defaults {
		if resolved, ok := resolveIfDir(c); ok {
			candidates = append(candidates, resolved)
		}
	}

	return candidates
}

// resolveIfDir checks that path exists and is a directory (following symlinks),
// returning a path suitable for filepath.Walk. Symlinks are resolved via
// EvalSymlinks; regular directories are returned as-is.
func resolveIfDir(path string) (string, bool) {
	linfo, err := os.Lstat(path)
	if err != nil {
		return "", false
	}
	if linfo.Mode()&os.ModeSymlink != 0 {
		resolved, err := filepath.EvalSymlinks(path)
		if err != nil {
			return "", false
		}
		info, err := os.Stat(resolved)
		if err != nil || !info.IsDir() {
			return "", false
		}
		return resolved, true
	}
	if !linfo.IsDir() {
		return "", false
	}
	return path, true
}

// InitProject creates the .hyoka directory structure at the given parent
// directory. It creates the sentinel directory and all standard subdirectories,
// plus a .gitignore that excludes reports/.
func InitProject(parentDir string) (string, error) {
	root := filepath.Join(parentDir, ProjectDirName)

	if err := os.MkdirAll(root, 0755); err != nil {
		return "", err
	}

	for _, sub := range ProjectSubdirs {
		if err := os.MkdirAll(filepath.Join(root, sub), 0755); err != nil {
			return "", err
		}
	}

	gitignorePath := filepath.Join(root, ".gitignore")
	gitignoreContent := "# Auto-generated by hyoka init\nreports/\n"
	if err := os.WriteFile(gitignorePath, []byte(gitignoreContent), 0644); err != nil {
		return "", err
	}

	return root, nil
}
