package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDiscoverProjectDir_Found(t *testing.T) {
	// Create a temp tree: root/.git + root/.hyoka/configs
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, ".git"), 0755)
	os.MkdirAll(filepath.Join(root, ".hyoka", "configs"), 0755)

	proj := DiscoverProjectDir(root)
	if !proj.Found() {
		t.Fatal("expected to find .hyoka directory")
	}
	if proj.Root != filepath.Join(root, ".hyoka") {
		t.Errorf("expected root %q, got %q", filepath.Join(root, ".hyoka"), proj.Root)
	}
}

func TestDiscoverProjectDir_FoundInParent(t *testing.T) {
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, ".git"), 0755)
	os.MkdirAll(filepath.Join(root, ".hyoka"), 0755)
	child := filepath.Join(root, "sub", "deep")
	os.MkdirAll(child, 0755)

	proj := DiscoverProjectDir(child)
	if !proj.Found() {
		t.Fatal("expected to discover .hyoka from child directory")
	}
	if proj.Root != filepath.Join(root, ".hyoka") {
		t.Errorf("expected root %q, got %q", filepath.Join(root, ".hyoka"), proj.Root)
	}
}

func TestDiscoverProjectDir_StopsAtGitRoot(t *testing.T) {
	// root/.hyoka exists but child/.git is present — discovery from child
	// should stop at child (the git root) and not find root/.hyoka.
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, ".hyoka"), 0755)

	child := filepath.Join(root, "child")
	os.MkdirAll(filepath.Join(child, ".git"), 0755)

	proj := DiscoverProjectDir(child)
	if proj.Found() {
		t.Errorf("should NOT discover .hyoka above git root, but found %q", proj.Root)
	}
}

func TestDiscoverProjectDir_NotFound(t *testing.T) {
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, ".git"), 0755)

	proj := DiscoverProjectDir(root)
	if proj.Found() {
		t.Errorf("expected no .hyoka directory, but found %q", proj.Root)
	}
}

func TestProjectDir_SubDir(t *testing.T) {
	proj := &ProjectDir{Root: "/repo/.hyoka"}
	got := proj.SubDir("configs")
	want := "/repo/.hyoka/configs"
	if got != want {
		t.Errorf("SubDir(configs) = %q, want %q", got, want)
	}

	empty := &ProjectDir{}
	if empty.SubDir("configs") != "" {
		t.Error("SubDir on empty project dir should return empty string")
	}
}

func TestInitProject(t *testing.T) {
	parent := t.TempDir()
	root, err := InitProject(parent)
	if err != nil {
		t.Fatalf("InitProject: %v", err)
	}

	expected := filepath.Join(parent, ProjectDirName)
	if root != expected {
		t.Errorf("InitProject returned %q, want %q", root, expected)
	}

	// Verify subdirectories
	for _, sub := range ProjectSubdirs {
		info, err := os.Stat(filepath.Join(root, sub))
		if err != nil {
			t.Errorf("missing subdirectory %q: %v", sub, err)
			continue
		}
		if !info.IsDir() {
			t.Errorf("%q should be a directory", sub)
		}
	}

	// Verify .gitignore
	data, err := os.ReadFile(filepath.Join(root, ".gitignore"))
	if err != nil {
		t.Fatalf("reading .gitignore: %v", err)
	}
	if got := string(data); got != "# Auto-generated by hyoka init\nreports/\n" {
		t.Errorf(".gitignore content = %q", got)
	}
}

func TestInitProject_Idempotent(t *testing.T) {
	parent := t.TempDir()

	// Init twice — should not fail
	if _, err := InitProject(parent); err != nil {
		t.Fatalf("first init: %v", err)
	}
	if _, err := InitProject(parent); err != nil {
		t.Fatalf("second init (idempotent): %v", err)
	}
}

func TestResolveCandidates(t *testing.T) {
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, ".hyoka", "configs"), 0755)
	os.MkdirAll(filepath.Join(root, "configs"), 0755)

	proj := &ProjectDir{Root: filepath.Join(root, ".hyoka")}

	// Save and restore working directory
	orig, _ := os.Getwd()
	defer os.Chdir(orig)
	os.Chdir(root)

	candidates := ResolveCandidates(proj, "configs")
	if len(candidates) < 1 {
		t.Fatal("expected at least one candidate")
	}
	// .hyoka/configs should come first
	if candidates[0] != filepath.Join(root, ".hyoka", "configs") {
		t.Errorf("first candidate should be .hyoka/configs, got %q", candidates[0])
	}
}

func TestResolveCandidates_NoProjectDir(t *testing.T) {
	root := t.TempDir()
	os.MkdirAll(filepath.Join(root, "prompts"), 0755)

	proj := &ProjectDir{} // not found

	orig, _ := os.Getwd()
	defer os.Chdir(orig)
	os.Chdir(root)

	candidates := ResolveCandidates(proj, "prompts")
	if len(candidates) < 1 {
		t.Fatal("expected at least one candidate from legacy paths")
	}
	// Should fall back to ./prompts
	if candidates[0] != "./prompts" {
		t.Errorf("expected ./prompts, got %q", candidates[0])
	}
}
